import React, { Component } from 'react';
import './App.css';
import Archie from './archie.jpg';

class App extends Component {
  render() {
    return (
      <div className="App">
        <h1>Archibald Robert Boyle</h1>
        <img src={Archie} />
        <div style={{padding: '0px 15%'}}>
          <p style={{textAlign: 'center'}}>Archibald Robert Boyle was a decorated British military hero who served in World War I and II. </p>
          <p style={{textAlign: 'center'}}>He was one of the most important figures in British Intelligence and Counter-Intelligence during World War II.</p>
          <p style={{textAlign: 'center'}}>Some of the positions he held include Air Commodore, Director of Security and Intelligence of the SOE (Special Operations Executive), Deputy Director of Intelligence in the RAF, Director of Intelligence at the Air Ministry, RAF Intelligence Chief and Member of the SOE Council. He was also was in the running (and by some historians considered the runner-up) for the position of Chief of the Secret Intelligence Service (known as SIS or MI6).</p>
        </div>
        <h2>Early Life and WWI</h2>
        <div style={{padding: '0px 7%'}}>
          <p>Archibald Robert Boyle was born August 11th, 1887. He attended Eagle House School in Sandhurst, England (from 1896 to 1900) before going to Bradfield College in Reading, England where he was captain of the cricket team. In 1907, Boyle started his military career at 20 years old.</p>
          <p>
              In World War I he was a Captain of the 1st Batallion of the Argyll and Sutherland Highlanders--part of the Royal Scots (Lothian Regiment).
              The 1st Batallion was part of the 81st Brigade within the 27th Division.
              While there is limited information of Boyle's time in WWI, records show he fought with his regiment in France on the Western Front and in Greece on the Struma Front (also known as the Macedonian or Salonica Front). Historical accounts of his Brigade would suggest that it is possible Boyle was deployed with the rest of the 81st Brigade in India (in 1914) and it almost certain that Boyle arrived in Le Havre (Normandy region of France) in December 1914 with the 1st Batallion.
              Boyle saw action in the Second Battle of Ypres in Belgium.
          </p>
          <h3>The Battle of St. Eloi and the Second Battle of Ypres</h3>
          <p>The battles of Ypres were an overall loss for the Allies. However, in the first battle, the Battle of St. Eloi (or Actions of St. Eloi Craters) the 27th Division saw the most advances for the Allied powers during either of these battles. The 27th Brigade took three German lines in one day. This was quick given how tough it was to advance in WWI trench warfare.</p>
          <p>For Boyle's brigade, the Second Battle of Ypres started with the Battle of St. Julien. From April 16th, Boyle's Battalion remained unrelieved in the trenches for eighteen days, subject to heavy shell fire and projectiles from minnewerfen as well as German chlorine gas attacks. Chlorine gas could cover larger areas than mustard gas and killed thousands of soldiers and civilians in these battles. While British soldiers came accross Canadian soldiers and Belgian civilians who warn them of the 'gas', they did not know what they were facing and did not receive gas masks until months later.
          The Battle of St. Julien ended May 5th and was roughly a stalemate or a German tactical victory as the Allies pushed back slightly from their original position.
          </p>
          <p>The Battle of Frezenberg Ridge (May 8th, 1915) and the Battle of Bellewaarde Ridge (May 24th, 1915) saw two more stalemates or slight German victories. In both Germans relied on gas attacks.</p>
          <p> While the Allies did not win these Battles, Boyle received a two Military Crosses in 1915 and his batallion was commended for "the excellent way in which they moved forward by digging and so prepared the way for the advance of those behind".</p>
          <h3>Struma Front</h3>
          <p>
            After the Second Battle of Ypres, the 81st brigade then travelled to Greece. Boyle's battalion saw action in The Capture of The Karajakois (September 30th, 1916), The Capture of Yenikoi (March 10th, 1916), the two battles at Tumbitza Farm (November 17th and December 6th, 1916), Capture of Homondos (October 14th, 1917), the Capture of the Roche Noire Salient (September 1st, 1918) and the Passage of The Vardar and Pursuit to the Strumica Valley (September 22nd, 1918). In most of these battles and captures the British raided Bulgarian troops around Dorian and the Struma Valley.
          </p>
          <p>The 1st Batallion would then move to the Black Sea (October 1st, 1918): when the 27th Divison continued its advance to Krupnik until it was order to go to the Black Sea. However, by this point it is unlikely Boyle was still with the 1st Battallion. At some point in 1918, Boyle switched from battlefield to the air and became a Squadron Leader in the Royal Air Force. He had some flying experience and but subsequently moved on to primarily conducting Air Intelligence.</p>
          <p><a href="https://www.forces-war-records.co.uk/maps/units/2204/81st-infantry-brigade/8875/1st-battalion/?registered=true&ident=2455285">Here</a> is a link to an interactive map of the movements of the 81st brigade during World War I.</p>
          <p>
            During his time on the Struma Front, Boyle received more decorations. He received a higher order of the Miltary Cross (Bar 1916). He also received the Knight's Cross of the Order of the White Eagle (OWE 5th Class), a Royal Order from the Kingdom of Serbia for protecting the Serbians from a combined attack from Germany, Austria-Hungary, the Ottoman Empire and Bulgaria. Lastly, Boyle was recognized as Officier of the Order of the British Empire (OBE) in 1919.
          </p>
        </div>
      <h2>WWII</h2>
      <div style={{padding: '0px 7%'}}>
        <p>Most of what we know about Boyle in World War II comes from letters from the Dominion's Office in the UK National Archives. Boyle and his colleagues wrote hundreds of letters, many of which were not made available until as late as 2003. These letters have been used as primary sources for modern day WW2 historical analysis of British Intelligence and Counter-Intelligence. However, much of these secret operations were never officially written down and historians have written that many secrets died with four men: Winston Churchill, Archibald Boyle, Captain Robertson and MI6 Chief Menzies. Often only these 4 men knew (as well as the relevant agent, double-agent or spy) secrets because they were afraid of leaks from within the British Army as well as future evaluation of difficult decisions that often determined which British soldiers, and sometimes civilians, would die.</p>
        <p>Due new needs from the war, the British restructured the Special Operations Executive to help deal with intelligence and counter-intelligence. It was the Security Section of the Special Operations Executive that was under the overall control of Commodore Archibald Robert Boyle. Boyle had gone from the infantry, to the RAF, to civil service, to the Foreign Office, to the Air Ministry (where he rose to the rank Assistant Under Secretary of State) to Air Commodore. At the start of WWII Air Commodore Buss was asked to step down so Boyle could take his position.</p>
        <h3>General Description</h3>
        <p>Boyle was held in high regard by all of his contacts, many valuable, including Winston Churchill. Aonghais Fyffe, a security officer, described him as a highly respected, kind and approachable man who was never dictatorial or domineering. Fyffe said Boyle would listen to briefings with his eye close while smoking a pipe. While kind, Boyle had a keen and suspicious mind, honed by 20 years of air intelligence experience. Another military officer described him as ‘very careful, shrewd and competent’.</p>
        <h3>SOE Experience</h3>
        <p>Boyle had a hand in a wide variety of matters. He oversaw security of SOE missions in North Africa, Egypt, Italy and India, attended met with members of the International Olympic Committee to discuss olympic matters, he interviewed agents and double-agents to help determine where their loyalties fell, he met with members of the Vichy government in hopes of gaining their support, he helped determine the informational sharing process between intelligence agencies, he served as the liaison between the SOE and other intelligence agencies (including MI5 and MI6) and had input with restructuring the hierarchy within the military bureaucracy. He was one of a few men who choose who got promoted within the SOE. </p>
        <p>Boyle also had influence regarding Inverlair Lodge or “The Cooler”, an internment camp for volunteers for secret operations who refused to take part once they knew the details of the mission or couldn’t complete their task. These men could not be return to civilian life during the war because of the information they held and risk that they would be killed. Boyle advocated for kind treatment of these individuals for reasons related to morality, security and public opinion. Boyle pointed out that they did not have enough men to guard the camp and therefore they should not want to create an environment from which individuals wanted to escape. Additionally, when word got out about the camp (during or after the war) Boyle did not like the optics of running a ‘concentration camp’ in Britain.</p>
        <p>While Boyle’s strengths included to his carefulness, intelligence, shrewdness, likability and experience, perhaps his most important quality was his ability to navigate the internal workings of the British Intelligence system, a landscape that had to adapt (often by his doing and at Churchill’s request) to Britain’s needs during an unprecedented war. Boyle knew when and when not to get intelligence officials to share information and collaborate, and how to ask or tell. His valuable military contacts repeatedly served him and his country well during the war.</p>
        <p>Boyle’s biggest role apart from overall security was that he was the primary source of intelligence for MI5’s double agents and from 1940 onward, is thought to have supplied the majority of the wireless messages sent by SNOW, SUMMER and TATE. This information, often true, was designed to be intercepted by the Germans and give double-agents legitimacy without actually helping the Germans too much. Other information was false, and some information’s veracity is not known today. For example, Boyle (with Churchill’s approval) gave the Germans “searchlight locations” in London. Often Boyle leaked information expendable areas as desirable targets. Sometimes they included residential districts (although some historians suggest Britain may have exaggerated the damage by some German bombings). This lead Home Secretary, and leader of the Labour Party, to protest Churchill and Boyle’s targets, saying “Who are we to play God?” Reactions such as these lead Churchill and Boyle to reduce the amount of security officials who knew about releasing target information to MI5’s wireless double agents, allowing Boyle to release information without alerting the War Cabinet, chiefs of staff, the Home Office, or other directors of intelligence. Churchill, Boyle and Captain Robertson were totally secure in their intelligence operations. In fact, the Wireless Board existed without the knowledge of chiefs of staff with no authority, no budget and no paper presence. This demonstrates that Boyle was one of Churchill’s most trusted men as it was extremely rare that so few men would have access to intelligence. </p>
        <h3>SNOW</h3>
        <p>Arthur Owens, a double agent who went by the British code name SNOW, was the first German agent to be turned by British Intelligence. While Owens, a Welsh nationalist, disliked the English to his death and occasionally helped the Nazis, he helped entrap other Nazi spies as part of the Double Cross system making him, overall, part of “possibly the most successful counter-espionage operation ever undertaken”. Run by the Twenty Committee also referred to as XX Committee (a play on Double Cross), SNOW helped detect every German agent in Britain and fed false information including the false location of D-Day landings.</p>
        <h3>TATE</h3>
        <p>Wulf Schmidt (code name Tate) was a Danish citizen that was parachuted into Britain as a spy by the Abwehr in 1940. He was turned into a double agent and was vital in convincing the Germans that the Allies weren’t were attacking Normandy during D-Day and were instead attacking southern France, the Balkans, Norway and Bulgaria. Even after the invasions, British Intelligence convinced the Germans temporarily that it was a diversion, and that previous German intelligence was correct. This delayed German reinforcements to the region for seven weeks.</p>
        <h3>D-Day</h3>
        <p>Boyle’s and Churchill’s work with double agents culminated to executing D-Day. In addition to fooling Germans through counter-intelligence, Boyle was in charge of implementing a travel ban before D-Day to protect the operation and he was in charge of lying to the rest of the British Military about the plan to prevent leaks from sabotaging the operation.</p>
        <h3>Post WWII</h3>
        <p>Two years after D-Day and a couple months after the end of the war, the SOE was officially dissolved in January 1946 as the SIS absorbed the SOE’s functions and the Special Operations Branch of the Secret Service was formed.</p>
        <p>During the war (in 1939) Boyle had received the Companion of St. Michael and St. George (CMG) on the recommendation of the Foreign Office. He did not receive any other awards on record, even though his most important work came from 1940 to 1945.</p>
        <p>After World War II Boyle was in charge of RAF Recruiting with a special mission to the Public Schools. Interested in the Boy Scout movement, he spent much of his spare time in South Lambeth where he was Commissioner. Boyle retired on January 1st, 1949 and it is believed he lived his remaining days in South Lambeth, a district in London. Three months after retiring he passed away on March 6th, 1949 at the age of 61.</p>
        <p>Oddly, the only representation of Boyle in film came in The Last Englishman, a movie about Alfred Daniel Wintle, referred to as one of the "greatest British eccentrics". Wintle, a member of the RAF, attempted to steal a plane and threatend (and perhaps shot at) then Air Commodore Boyle. The movie falsely portrays Wintle's threats as heroic and Boyle as a small, smug and cowardly military bureaucrat. Footage can be seen <a href="http://www.youtube.com/watch?v=jowJELNfACA&t=6m9s">here</a>.</p>
      </div>
    <div style={{height: '100px', width: "100%"}}></div>
      </div>
    );
  }
}

export default App;
